version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: data-redis
    restart: always
    volumes:
      - ./runtime/redis:/data:rw
  data-server:
    build: .
    container_name: data-server
    restart: always
    command: pm2-runtime start pm2.json
    ports:
      - '3000:3000'
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - './runtime:/home/makerTransationData/runtime'
      - './pm2.json:/home/makerTransationData/pm2.json'

