version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: data-redis
    restart: always
    volumes:
      - ./runtime/redis:/data:rw
    ports:
      - "6389:6379"
  data-server:
    build: .
    container_name: data-server
    restart: always
    command: pm2-runtime start pm2.json
    ports:
      - '8001:8001'
      - '3000:3000'
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - './runtime:/home/makerTransationData/runtime'
      - './pm2.json:/home/makerTransationData/pm2.json'
  rabbitmq:
    restart: always
    image: bitnami/rabbitmq:latest
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_USERNAME: test
      RABBITMQ_PASSWORD: 123456
    volumes:
      - ./rabbit:/bitnami

