version: '3.8'
services:
  redis:
    image: redis:latest
    restart: always
    volumes:
      - ./runtime/redis:/data:rw
  data-server:
    build: .
    restart: always
    command: pm2-runtime start pm2.json
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - './runtime:/app/runtime'
      - './pm2.json:/app/pm2.json'
      - './src/config/:/app/src/config/'

