version: '3.8'
services:
  redis:
    image: redis:latest
    restart: always
    volumes:
      - ./runtime/redis:/data:rw
  data-server:
    build: .
    restart: always
    command:
      - sh
      - -c
      - |
        curl -o /app/boot-time.txt http://worldtimeapi.org/api/timezone/Asia/Hong_Kong &
        yarn run postinstall &
        pm2-runtime start pm2.json
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - './runtime:/app/runtime'
      - './pm2.json:/app/pm2.json'
      - './boot-time.txt:/app/boot-time.txt'
