version: '3.8'
services:
  redis:
    build: ./redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "16033:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./redis/data:/data:rw
      - ./redis/logs:/logs
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
  data-server:
    build: .
    restart: always
    command:
      - sh
      - -c
      - |
        curl -o /app/boot-time.txt http://worldtimeapi.org/api/timezone/Asia/Hong_Kong &
        yarn run postinstall &
        pm2-runtime start pm2.json
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - './runtime:/app/runtime'
      - './pm2.json:/app/pm2.json'
      - './boot-time.txt:/app/boot-time.txt'
